-- core.group  --
-- DLL File ---

-- Create table: core."group

		CREATE TABLE core."group" (
			group_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
			CONSTRAINT group_pk PRIMARY KEY (group_id)
		);
		COMMENT ON TABLE core."group" IS '';
	

-- =============================================
-- FIELDS 
-- =============================================




-- **** group_name *******************************************

-- ADD Column

		ALTER TABLE core."group" ADD group_name text NOT NULL DEFAULT '';
		COMMENT ON COLUMN core."group".group_name IS '';
	
-- MODIFY Column

		ALTER TABLE core."group" 
			ALTER COLUMN group_name TYPE text,
			ALTER COLUMN group_name SET DEFAULT '',
			ALTER COLUMN group_name SET NOT NULL;
		COMMENT ON COLUMN core."group".group_name IS '';
	

-- Foreign Key Constraint


-- Remove Constraint if Available
ALTER TABLE core."group" DROP CONSTRAINT group_name;



-- **** group_descr *******************************************

-- ADD Column

		ALTER TABLE core."group" ADD group_descr text NOT NULL DEFAULT '';
		COMMENT ON COLUMN core."group".group_descr IS '';
	
-- MODIFY Column

		ALTER TABLE core."group" 
			ALTER COLUMN group_descr TYPE text,
			ALTER COLUMN group_descr SET DEFAULT '',
			ALTER COLUMN group_descr SET NOT NULL;
		COMMENT ON COLUMN core."group".group_descr IS '';
	

-- Foreign Key Constraint


-- Remove Constraint if Available
ALTER TABLE core."group" DROP CONSTRAINT group_descr;



-- **** group_isdisabled *******************************************

-- ADD Column

		ALTER TABLE core."group" ADD group_isdisabled boolean NOT NULL DEFAULT false;
		COMMENT ON COLUMN core."group".group_isdisabled IS '';
	
-- MODIFY Column

		ALTER TABLE core."group" 
			ALTER COLUMN group_isdisabled TYPE boolean,
			ALTER COLUMN group_isdisabled SET DEFAULT false,
			ALTER COLUMN group_isdisabled SET NOT NULL;
		COMMENT ON COLUMN core."group".group_isdisabled IS '';
	

-- Foreign Key Constraint


-- Remove Constraint if Available
ALTER TABLE core."group" DROP CONSTRAINT group_isdisabled;



-- **** _createby *******************************************

-- ADD Column

		ALTER TABLE core."group" ADD _createby bigint NULL ;
		COMMENT ON COLUMN core."group"._createby IS '';
	
-- MODIFY Column

		ALTER TABLE core."group" 
			ALTER COLUMN _createby TYPE bigint,
			ALTER COLUMN _createby DROP DEFAULT,
			ALTER COLUMN _createby DROP NOT NULL;
		COMMENT ON COLUMN core."group"._createby IS '';
	

-- Foreign Key Constraint


-- Remove Constraint if Available
ALTER TABLE core."group" DROP CONSTRAINT _createby;

-- ADD Constraint

					ALTER TABLE core."group"
						ADD CONSTRAINT _createby
						FOREIGN KEY (_createby)
						REFERENCES core."user"(user_id)
				



-- **** _createdate *******************************************

-- ADD Column

		ALTER TABLE core."group" ADD _createdate timestamp WITH TIME ZONE NOT NULL DEFAULT (now());
		COMMENT ON COLUMN core."group"._createdate IS '';
	
-- MODIFY Column

		ALTER TABLE core."group" 
			ALTER COLUMN _createdate TYPE timestamp WITH TIME ZONE,
			ALTER COLUMN _createdate SET DEFAULT (now()),
			ALTER COLUMN _createdate SET NOT NULL;
		COMMENT ON COLUMN core."group"._createdate IS '';
	

-- Foreign Key Constraint


-- Remove Constraint if Available
ALTER TABLE core."group" DROP CONSTRAINT _createdate;



-- **** _modifyby *******************************************

-- ADD Column

		ALTER TABLE core."group" ADD _modifyby bigint NULL ;
		COMMENT ON COLUMN core."group"._modifyby IS '';
	
-- MODIFY Column

		ALTER TABLE core."group" 
			ALTER COLUMN _modifyby TYPE bigint,
			ALTER COLUMN _modifyby DROP DEFAULT,
			ALTER COLUMN _modifyby DROP NOT NULL;
		COMMENT ON COLUMN core."group"._modifyby IS '';
	

-- Foreign Key Constraint


-- Remove Constraint if Available
ALTER TABLE core."group" DROP CONSTRAINT _modifyby;

-- ADD Constraint

					ALTER TABLE core."group"
						ADD CONSTRAINT _modifyby
						FOREIGN KEY (_modifyby)
						REFERENCES core."user"(user_id)
				



-- **** _modifydate *******************************************

-- ADD Column

		ALTER TABLE core."group" ADD _modifydate timestamp WITH TIME ZONE NULL ;
		COMMENT ON COLUMN core."group"._modifydate IS '';
	
-- MODIFY Column

		ALTER TABLE core."group" 
			ALTER COLUMN _modifydate TYPE timestamp WITH TIME ZONE,
			ALTER COLUMN _modifydate DROP DEFAULT,
			ALTER COLUMN _modifydate DROP NOT NULL;
		COMMENT ON COLUMN core."group"._modifydate IS '';
	

-- Foreign Key Constraint


-- Remove Constraint if Available
ALTER TABLE core."group" DROP CONSTRAINT _modifydate;

-- Clear All Unique Constraint


-- Recreate Unique Constraint

				ALTER TABLE  core."group"
					ADD CONSTRAINT group_name UNIQUE (group_name);			
			
